Assignment 2 files
FacultadInformatica-LinkedData/Curso2020-2021 pull request #101
Opened 2020-09-12 12:47 UTC by mcaminome

2020-09-12 12:50 UTC, ocorcho requested changes

2020-09-12 12:50 UTC, ocorcho commented on Assignment2/mcaminome-MacarenaCamino.ttl
> +		:Measurement8401	measurement:hasTemperature:"29"^^xsd:integer;
Have you tried with a validator? You should always try to leave a blank space (at least) between elements in the triple

2020-09-17 18:37 UTC, mcaminome reviewed
Update Assignment 2 and upload assignment 2b

2020-09-20 07:40 UTC, ocorcho commented
Assignments 1 and 2 are now complete. 
Now @paoespinozarias will check assignment 2b

2020-09-20 09:21 UTC, paoespinozarias requested changes

2020-09-20 09:21 UTC, paoespinozarias commented on Assignment2/mcaminome-fromJSONtoJSON-LD.jsonld
> +  	"people": "http://www.oeg-upm.net/ontologies/people",
Add / or # at the end of your URI definition

2020-09-20 09:24 UTC, paoespinozarias commented on Assignment2/mcaminome-fromJSONtoJSON-LD.jsonld
> +    "father":"parents:father",
These attribute definitions work, but semantically they aren't ok. The best way is to use a prefix and add the name of the concept/property you want to use e.g. "mother":"yourvocab:mother".
The same comment applies to the combination you did in the subject attributes definition. 
You don't need to change them, but remember to provide good definitions for the future.

2020-09-20 09:24 UTC, paoespinozarias commented on Assignment2/mcaminome-fromRDFtoJSON-LD.jsonld
> +}
This file is ok.

2020-10-04 16:01 UTC, ocorcho commented
I am surprised that you have not taken into account the latest set of comments provided by @paoespinozarias 
Given this situation, I have decided to close this pull request and not accept anything that has been submitted. Contact us directly if you wish your work to be considered.

2020-10-04 16:01 UTC, closed without merging