Add files via upload
FacultadInformatica-LinkedData/Curso2020-2021 pull request #177
Opened 2020-09-14 12:35 UTC by marttamayy

2020-09-14 15:49 UTC, ocorcho requested changes

2020-09-14 15:49 UTC, ocorcho commented on Assignment2/marttamayy-Marta Mayoral.ttl
> +:Measurement8401 vocab:hasTemperature :29;
Syntax error. Will not parse. Same in the following lines

2020-09-16 10:11 UTC, marttamayy reviewed
I checked the .ttl document and I made the requested changes.

2020-09-16 10:14 UTC, ocorcho requested changes

2020-09-16 10:14 UTC, ocorcho commented on Assignment2/marttamayy-Marta Mayoral.ttl
> +:Measurement8401 data:hasTemperature :"29"^^xsd:float;
there are still syntax errors here. Please parse this in a validator first.

2020-09-16 10:28 UTC, marttamayy reviewed
I'm sorry, i sent the wrong one, this one shouldn't have any syntax error.

2020-09-16 10:38 UTC, merged