mdelucasg-fromRDFtoJSON-LD.jsonld
FacultadInformatica-LinkedData/Curso2020-2021 pull request #215
Opened 2020-09-14 19:47 UTC by mdelucasg

Antes había solicitado el PullREquest con un archivo equivocado.
Perdón.

2020-09-15 20:34 UTC, paoespinozarias requested changes
Please, validate your code before submmit it. You can use json-ld playground. There are syntax errors and also structure ones:

2020-09-15 20:34 UTC, paoespinozarias commented on Assignment2/mdelucasg-fromRDFtoJSON-LD.jsonld
> +},
(This comment applies to all this file. Please, validate your code before submitting it. There are some syntax errors. You might use the json-ld playground online tool to test it. )

Your prefixes are wrong, check how they should be defined. Also, check the “sample” URI, something is missing at the end.

2020-09-15 20:34 UTC, paoespinozarias commented on Assignment2/mdelucasg-fromRDFtoJSON-LD.jsonld
> +]"
This way to define the JSON-LD is ok, but you are missing another tag that should be used when you want to define data inside a named graph (@graph).

Finally, remember that Class, Sensor, Computer, User, and Measurement are different objects (each of them has its own attributes) so provide different types for them (not use “sample:elements” for all).

2020-09-15 20:34 UTC, paoespinozarias commented on Assignment2/mdelucasg-fromJSONtoJSON-LD.jsonld
> +{
Please, validate the code and fix the syntaxs errors.

2020-09-17 19:39 UTC, mdelucasg commented
I have checked all the syntax problems. Ignore the changes in the mdelucasg.ttl file (I don't know how to remove it from this pull request)

2020-09-17 20:34 UTC, paoespinozarias requested changes

2020-09-17 20:34 UTC, paoespinozarias commented on Assignment2/mdelucasg-fromJSONtoJSON-LD.jsonld
> +	"@type": "Person>",
Wrong definition, delete >

2020-09-17 20:34 UTC, paoespinozarias commented on Assignment2/mdelucasg-fromJSONtoJSON-LD.jsonld
> +	 	"@type": "CollegeOrUniversity",
UPM is a University thus we can define it as "@type":"University"

2020-09-17 20:34 UTC, paoespinozarias commented on Assignment2/mdelucasg-fromRDFtoJSON-LD.jsonld
> +}
It is ok, Well done!

2020-09-18 07:29 UTC, mdelucasg commented
Done it!

2020-09-19 20:03 UTC, paoespinozarias approved these changes

2020-09-19 20:03 UTC, merged