Update 2b
FacultadInformatica-LinkedData/Curso2020-2021 pull request #235
Opened 2020-09-17 15:15 UTC by manumazvi

2020-09-17 18:12 UTC, paoespinozarias requested changes

2020-09-17 18:12 UTC, paoespinozarias commented on Assignment2/manumazvi-fromJSONtoJSON-LD.jsonld
> +		"name":"subjects:name",
You have a duplicate name. Rename it, maybe as "subject":"vocab:subject" according to the name provided at the structure of your subject's array.

2020-09-17 18:12 UTC, paoespinozarias commented on Assignment2/manumazvi-fromJSONtoJSON-LD.jsonld
> +	"@id":" http://example.com/semweb/people/",
delete blank space " h

2020-09-17 18:12 UTC, paoespinozarias commented on Assignment2/manumazvi-fromJSONtoJSON-LD.jsonld
> +	"subjets":
Typo, it should be "subjects"

2020-09-17 18:12 UTC, paoespinozarias commented on Assignment2/manumazvi-fromRDFtoJSON-LD.jsonld
> +    "xsd": <http://www.w3.org/2001/XMLSchema#>
They shouldn't be defined between <>
Also, there is something missing at the end of the URI of "prefix"

2020-09-24 19:16 UTC, paoespinozarias commented
Requested changes on Assignment 2b are still pending. Meanwhile, @ocorcho can review Assignment 3

2020-09-28 09:26 UTC, paoespinozarias commented
Requested changes on Assignment 2b. In the meantime, @ocorcho and @dachafra can review Assignment 3 and Assignment 4

2020-09-28 10:27 UTC, ocorcho commented
Assignment 3 is ok

2020-10-04 16:04 UTC, ocorcho commented
@dachafra Check this assignment to see if it can be accepted and closed.

2020-10-04 16:07 UTC, dachafra commented
sorry! A4 is okay, merging...

2020-10-04 16:07 UTC, merged