assignment2b
FacultadInformatica-LinkedData/Curso2020-2021 pull request #240
Opened 2020-09-17 17:42 UTC by alejandrofdezmerino

2020-09-17 19:03 UTC, paoespinozarias requested changes

2020-09-17 19:03 UTC, paoespinozarias commented on Assignment2/alejandrofdezmerino-fromRDFtoJSON-LD.jsonld
> +},
"includes", "hasOwner", "hasMeasurement" are missing.

2020-09-17 20:40 UTC, alejandrofdezmerino commented
New update assignment 2b

2020-09-17 21:42 UTC, paoespinozarias requested changes

2020-09-17 21:42 UTC, paoespinozarias commented on Assignment2/alejandrofdezmerino-fromJSONtoJSON-LD.jsonld
> +	"name": "Alejandro Fernandez Merino",
Still pending to add "@type"

2020-09-17 21:42 UTC, paoespinozarias commented on Assignment2/alejandrofdezmerino-fromJSONtoJSON-LD.jsonld
> +	"subjects":	{
Define it as an array [ ]
Then you don't need to define "subject1": , "subject2": ,etc. Delete these names and leave only the name, teachers, description values inside curly braces.

2020-09-18 13:15 UTC, alejandrofdezmerino commented
New update assignment 2b

2020-09-18 16:33 UTC, paoespinozarias approved these changes

2020-09-18 16:34 UTC, merged