Assignment 2b
FacultadInformatica-LinkedData/Curso2020-2021 pull request #255
Opened 2020-09-18 10:19 UTC by LuisLopezPi

2020-09-19 12:59 UTC, paoespinozarias commented on Assignment2/LuisLopezPi-fromJSONtoJSON-LD.jsonld
> +		"teacher": "subjects:teacher"
These subject attribute definitions work, but semantically they aren't ok. The best way to define them might be defining a new prefix for the subject concept and then use it to define their attributes.
You don't need to change them, but remember to provide good definitions for the future.

2020-09-19 13:01 UTC, paoespinozarias commented on Assignment2/LuisLopezPi-fromJSONtoJSON-LD.jsonld
> +}
This file is ok, well done.

2020-09-19 13:03 UTC, paoespinozarias requested changes

2020-09-19 13:03 UTC, paoespinozarias commented on Assignment2/LuisLopezPi-fromRDFtoJSON-LD.jsonld
> +	"User10A":"Computer101:User10A",
You are defining them as "@type" on your data, thus you don't need to define them here.

2020-09-19 13:03 UTC, paoespinozarias commented on Assignment2/LuisLopezPi-fromRDFtoJSON-LD.jsonld
> +			"Sensor029":{
You don't need to define "Sensor029". It isn't an attribute, it is a resource, thus I suggest you to remove it. Remember that when you define a resource, you only have to use curly braces and define inside all the resource attributes. However, when you have to specify a relationship between resources is when you have to define it as an attribute, for example as you did with the attribute "hasMeasurement" for defining the relationship between Sensor029 and Measurment8401. Note that "hasMeasurement" must be defined in the @context as you have done.
This comment also applies for "Measurement8401", "Computer101", and "User10A".

2020-09-28 08:08 UTC, paoespinozarias reviewed
Assignment 2b is ok. Please, @ocorcho review Assignment 3

2020-09-28 08:16 UTC, ocorcho commented
Assignment 3 is ok, but you have to rename the files as suggested (inside your own folder/directory) so that there are no conflicts.

2020-10-04 16:06 UTC, ocorcho commented
Given that the changes requested by me 6 days ago have not been dealt with, we are closing this pull request.
If you want this to be considered further, please contact us by e-mail.

2020-10-04 16:06 UTC, closed without merging