Assignment-2b
FacultadInformatica-LinkedData/Curso2020-2021 pull request #269
Opened 2020-09-18 13:17 UTC by inigoar

2020-09-19 17:38 UTC, paoespinozarias requested changes

2020-09-19 17:38 UTC, paoespinozarias commented on Assignment2/inigoar-fromJSONtoJSON-LD.jsonld
> +
You forgot to include the id.

2020-09-19 17:38 UTC, paoespinozarias commented on Assignment2/inigoar-fromRDFtoJSON-LD.jsonld
> + "Class01": {
You don't need to include the "Class01" attribute.

2020-09-19 17:38 UTC, paoespinozarias commented on Assignment2/inigoar-fromRDFtoJSON-LD.jsonld
> +        "Sensor029": {
You don't need to define "Sensor029". It isn't an attribute, it is a resource, thus I suggest you to remove it. Remember that when you define a resource, you only have to use curly braces and define inside all the resource attributes. However, when you have to specify a relationship between resources is when you have to define it as an attribute, for example as you did with the attribute "hasMeasurement" for defining the relationship between Sensor029 and Measurment8401. Note that "hasMeasurement" must be defined in the @context as you have done.
This comment also applies for "Measurement8401", "Computer101", and "User10A".

2020-09-21 15:10 UTC, inigoar commented
updated assignment2 and finished assignment3

2020-09-21 15:15 UTC, inigoar reviewed
updated

2020-09-21 18:43 UTC, paoespinozarias commented
Assignment 2b is ok. Now @ocorcho will review Assignment 3

2020-09-21 18:44 UTC, paoespinozarias reviewed
ok

2020-09-22 18:53 UTC, merged