Assigment2b
FacultadInformatica-LinkedData/Curso2020-2021 pull request #279
Opened 2020-09-18 14:56 UTC by pgandoy

![PabloGandoy](https://user-images.githubusercontent.com/71141513/93612189-7c77e480-f9cf-11ea-8d4c-c5584df8f085.jpg)

2020-09-19 19:27 UTC, paoespinozarias requested changes

2020-09-19 19:27 UTC, paoespinozarias commented on Assignment2/PabloGandoy.json
> +}
This file has syntax erros. Validate it before resubmiting.

2020-09-19 19:27 UTC, paoespinozarias commented on Assignment2/PabloGandoyJSONtoJSONLD.json-ld
> +}
This file has syntax erros. Validate it before resubmiting.

2020-09-20 08:02 UTC, ocorcho commented
Assignment 2a is ok

2020-09-20 09:02 UTC, paoespinozarias requested changes

2020-09-20 09:02 UTC, paoespinozarias commented on Assignment2/PabloGandoyRDFtoJSONLD.json-ld
> +}
This file has syntax errors. Validate it before resubmitting.

2020-09-21 22:31 UTC, paoespinozarias requested changes

2020-09-21 22:31 UTC, paoespinozarias commented on Assignment2/PabloGandoyJSONtoJSONLD.json-ld
> +@context:{
Missing " "

2020-09-21 22:31 UTC, paoespinozarias commented on Assignment2/PabloGandoyJSONtoJSONLD.json-ld
> +"name":"Pablo Gandoy",
Include a type and id

2020-09-21 22:32 UTC, paoespinozarias commented on Assignment2/PabloGandoyRDFtoJSONLD.json-ld
> +}
Now, it is ok!

2020-09-22 18:58 UTC, ocorcho commented
assignment 2a is now fixed.

2020-10-26 08:49 UTC, ocorcho commented
Requests done by @paoespinozarias have not been fixed, so we close this pull request.

2020-10-26 08:49 UTC, closed without merging