Assignment 2b
FacultadInformatica-LinkedData/Curso2020-2021 pull request #281
Opened 2020-09-18 15:18 UTC by patin9

2020-09-18 15:29 UTC, patin9 commented
Sorry, I committed the files yesterday but forgot to ask for the pull request.

2020-09-20 08:58 UTC, paoespinozarias requested changes

2020-09-20 08:58 UTC, paoespinozarias commented on Assignment2/patin9-fromJSONtoJSON-LD.jsonld
> +	"name": "Eva Tagarro",
Add the. "@id" and "@type"

2020-09-20 08:59 UTC, paoespinozarias commented on Assignment2/patin9-fromRDFtoJSON-LD.jsonld
> +}
This file is ok.

2020-09-21 22:18 UTC, paoespinozarias commented on Assignment2/patin9-fromJSONtoJSON-LD.jsonld
> +	"name": "Eva Tagarro",
Be careful when reusing prefixes. You don't have any assignment prefix on your context definitions. The correct definition is "@type": "assign:student"

2020-09-21 22:19 UTC, paoespinozarias reviewed
Assignment 2b is ok. Now @ocorcho will review Assignment 3

2020-09-22 18:52 UTC, merged