Update Assignment3
FacultadInformatica-LinkedData/Curso2020-2021 pull request #316
Opened 2020-09-23 14:45 UTC by ruliii

2020-09-25 11:33 UTC, ocorcho commented
Assignment 3 is ok. Now @dachafra to check assignment 4.

2020-09-25 11:40 UTC, dachafra requested changes

2020-09-25 11:40 UTC, dachafra commented on Assignment4/ruliii-w140455/task06.py
> +g.add((ns.Researcher,ns.ResearcherName,ns.JaneSmith))
this is not correct, Jane Smith should be declared as a resource and should belong to the class researcher

2020-09-25 11:40 UTC, dachafra commented on Assignment4/ruliii-w140455/task06.py
> +g.add((ns.JohnSmith,ns.WorksIn,ns.UPM))
and UPM is??? is not a university?

2020-09-25 11:40 UTC, dachafra commented on Assignment4/ruliii-w140455/task07.py
> +q3 = prepareQuery('''
this is not correct, you should retrieve all the triples belong to each individual annotated as person

2020-09-25 12:29 UTC, dachafra commented on Assignment4/ruliii-w140455/task06.py
> +g.add((ns.JaneSmith,RDF.type,ns.ResearcherName,))
still wrong, and also bad syntaxis.

2020-09-28 07:41 UTC, rgcmme commented
The hands-on part looks good. Once the assignments are ready it can be merged.

2020-09-28 10:30 UTC, dachafra approved these changes

2020-09-28 10:30 UTC, dachafra commented
assignmet4 ok

2020-09-28 10:31 UTC, merged