entrega 4 wnicolait
FacultadInformatica-LinkedData/Curso2020-2021 pull request #355
Opened 2020-09-25 19:34 UTC by wnicolait

2020-09-26 09:34 UTC, dachafra commented on Assignment4/wnicolait-80097/task06.py
> +g.add((nsP.Universithy, RDF.type, RDFS.Class))
University, not Universithy.

2020-09-26 09:34 UTC, dachafra commented on Assignment4/wnicolait-80097/task06.py
> +nsP = Namespace("http://Universithy/")
these namespaces are not right

2020-09-26 09:34 UTC, dachafra commented on Assignment4/wnicolait-80097/task06.py
> +g.add((nsPer.Person, RDF.type, RDFS.Class))
why are you creating the class person?

2020-09-26 09:35 UTC, dachafra commented on Assignment4/wnicolait-80097/task06.py
> +app = nsPer.Researcher
no no, review it!

2020-09-26 09:36 UTC, dachafra commented on Assignment4/wnicolait-80097/task06.py
> +"""**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**"""
ufff read carefully the tasks please, these lines are copy-paste from previous tasks

2020-09-26 09:37 UTC, dachafra commented on Assignment4/wnicolait-80097/task06.py
> +"""**TASK 6.4: Add to the individual JaneSmith the fullName, given and family names**"""
what about the other properties? given and family name

2020-09-26 09:38 UTC, dachafra commented on Assignment4/wnicolait-80097/task06.py
> +resource = (app, VCARD.FN, inv)
you are saying here: UNiversity has a full name that is John Smith

2020-09-26 09:39 UTC, dachafra commented
Please, review my comments, and do the tasks from Scratch after reading and testing carefully the examples. The lines you program do not have any sense

2020-09-26 09:40 UTC, dachafra requested changes
review from scratch

2020-09-28 15:32 UTC, dachafra commented on Assignment4/wnicolait-80097/task06(1).py
> +g.add((ns.Person, RDF.type, RDFS.subClassOf))
you are saying here that person is type of sublcassof, does not make sense

2020-09-28 15:33 UTC, dachafra commented on Assignment4/wnicolait-80097/task07(1).py
>  """**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**"""
where is the sparql query?

2020-09-28 15:33 UTC, dachafra commented on Assignment4/wnicolait-80097/task07(1).py
>  qt = prepareQuery('''
this does not make sense, please read carefully what the task7.3 is asking for

2020-09-28 15:34 UTC, dachafra requested changes
make the corresponding changes, there are many issues to solve

2020-10-04 16:08 UTC, ocorcho commented
Given that the changes requested by @dachafra 6 days ago have not been dealt with, we are closing this pull request.
If you want this to be considered further, please contact us by e-mail.

2020-10-04 16:08 UTC, closed without merging