Assingment3, Assignment4 & HandsOn
FacultadInformatica-LinkedData/Curso2020-2021 pull request #386
Opened 2020-09-27 11:49 UTC by aelxfun200

I upload all because the Pull request for Assigment3 was not closed.

2020-09-27 15:25 UTC, ocorcho commented
Assignment 3 is ok. Now @paoespinozarias will check assignment 2b, @dachafra will check assignment 4 and @rgcmme will check group assignment 1

2020-09-28 07:30 UTC, rgcmme commented
The self-assessment file is not filled. It is just a matter of putting an x between the brackets for those items satisfied.

2020-09-28 14:27 UTC, dachafra requested changes
6.3: Create a new individual of Researcher named "Jane Smith" is not correct, it is asking to create a new instance of Researcher, please change it
T7.2 and T7.3 are also wrong, prefixes are not used correctly, and queries do not make sense, take a look to contributions from your colleagues

2020-09-28 16:57 UTC, paoespinozarias requested changes

2020-09-28 16:57 UTC, paoespinozarias commented on Assignment2/aelxfun200-fromRDFtoJSON-LD.jsonld
> +}
The relationships "includes" between a Sensor and a Computer are missing. Also, the relationship "hasMeasurement" is missing. Please, take a look at the assignments that have been already accepted and make the needed changes.

2020-10-01 18:28 UTC, aelxfun200 commented
Cabe mencionar que en los ficheros de HandsOn hemos contribuido todos aunque haya subido yo los archivos directamente a mi repositorio.

2020-10-01 18:31 UTC, closed without merging