handsOn4 y modificacion handsOn3
FacultadInformatica-LinkedData/Curso2020-2021 pull request #505
Opened 2020-10-06 18:47 UTC by bbazzis

2020-10-07 09:43 UTC, dachafra requested changes
good first try! good luck with the enhanced version ;-)

2020-10-07 09:43 UTC, dachafra commented on HandsOn/Group56/mappings/zonasVerdes.yml
> +      - [gtfs:distrito, $(Distrito),xsd:string]
why you are using the gtfs prefix? I think you have to change it by the one you've defined

2020-10-07 09:43 UTC, dachafra commented on HandsOn/Group56/mappings/zonasVerdes.yml
> +prefixes:
General comment: I went to the ontology and I see that you have defined 8 classes, so you have to have, at least, 8 TriplesMap (not one), where you define the rule to generate the subject of each class and its associated Data and Object Properties.  For this second step, predicate object maps definition (po) you have to go Data and Object Properties and see where the domains of these properties are equal to the class of the triplesMap. For example, for district, you will have something like 
```
mappingDistrict:
    sources:
      - [ZonasVerdes-updated.csv~csv]
    s: http://group56.org/zonas-verdes/District/$(Distrito)
    po:
     - [a, ex:District]
     - [ex:nombreDistrito, $(Distrito)]
   (and more)
```

Remember to go to the individual's resource name strategy and see what should be the uris for your subjects (I didn't find it In your folder but I assume that would be something like: http://group56.org/zonas-verdes/District/$(District)

2020-10-07 17:03 UTC, dachafra requested changes
well done!!! Now we are still missing the object properties from the ontology. What we have to do is to define relations among the different triplesMaps. For example, you have defined an object property:
```
:tieneCalle rdf:type owl:ObjectProperty ;
            rdfs:domain :Distrito ;
            rdfs:range :SituacionDestino .
```

So we have to go to the triplesMap of Distrito and put:
```
  distrito:
    sources:
      - [ZonasVerdes-updated.csv~csv]
    s: http://group56.org/zonas-verdes/Districto/$(Distrito)
    po:
      - [a, ex:Distrito]
      - [ex:distrito, $(Distrito),xsd:string]  
      -p: ex:tieneCalle
         o:
             mapping: situaciondestino

```
And do it for all the object properties.

2020-10-08 08:52 UTC, bbazzis commented
En esta entrega hemos tenido que cambiar el tamaño del csv para poder entregarlo ya que nos generaba un output.nt muy grande por ello todos los archivos con un 100 en el nombre simbolizan este cambio.

2020-10-08 08:52 UTC, dachafra commented
perfect!!

2020-10-08 09:02 UTC, dachafra commented
Ahora tiene muy buena pinta! He estado mirando vuestra ontología y tenes Data properties como :nombreCalle que no aparecen en el mapping, deberían estar como parte de los PO de sus respectivas clases. Es decir, los data properties te dicen los predicateObjectMaps "simples" que debes definir. El triplesMaps donde se definan es dónde se estén definiendo las instancias de la clase en la cual dicha clase es el dominio de ese data property. Vamos con un ejemplo

en la ontología tenéis el data property
```
:nombreCalle rdf:type owl:DatatypeProperty ;
             rdfs:domain :SituacionDestino ;
             rdfs:range xsd:string .
```

Nos vamos al mapping de SituacionDestino y ponemos
```
  situaciondestino:
    sources:
      - [ZonasVerdes-updated.csv~csv]
    s: http://group56.org/zonas-verdes/SituacionDestino/$(Situacion_Destino)
    po:
      - [a, ex:SituacionDestino]
      - [es:nombreCalle, $(ELVALORQUESEA),xsd:string]
```

De hecho el predicado que tenéis ahora ex:SituacionDestino no existe en la ontología. Y si después miro al ontología para hacer mis consultas en SPARQL, y no habéis definido ese predicado, siempre me va a devolver vacio ;-) (
(lo explicaré en clase mañana)

Y con esto ya lo tendriáis perfecto!

2020-10-09 13:25 UTC, dachafra commented
great work, well done!!!

2020-10-09 13:25 UTC, dachafra approved these changes

2020-10-09 13:25 UTC, merged