HandsOn Assignment 4
FacultadInformatica-LinkedData/Curso2020-2021 pull request #511
Opened 2020-10-07 19:18 UTC by ziader

Con los compañeros de equipo:

@derbeire 
@AlvaroMK 
@yokernorris
@eduardogeuens

2020-10-07 19:19 UTC, ziader commented
changehistory.json y el archivo .csv modificado

2020-10-13 08:27 UTC, dachafra requested changes
change the POM seEncuentraEn by a proper join condition using coord_x as the field for the condition

2020-10-13 08:27 UTC, dachafra commented on HandsOn/Group37/mappings/archivo.yml
> +      - [base:seEncuentraEn,http://www.semanticweb.org/ontologies/2020/8/untitled-ontology-4/$(coord_x)~iri]
this is not correct, you have to perform a join condition

2020-10-13 17:44 UTC, ziader commented
Hemos modificado los archivos para incluir una relación join

2020-10-13 18:27 UTC, dachafra approved these changes

2020-10-13 18:27 UTC, merged