ultimate ref generation
FacultadInformatica-LinkedData/Curso2020-2021 pull request #542
Opened 2020-10-13 13:44 UTC by isa43

2020-10-13 15:52 UTC, dachafra requested changes
make the changes in the join conditions, rest ok

2020-10-13 15:52 UTC, dachafra commented on HandsOn/Group17/mappings/yarrrml_mapping.yml
> +      - p: vocab:mide
1) syntax is not correct
2) you need to specify the conditions.

Let me put an example

```
- p: vocab:estaEnEstacion
  o: 
    - mapping: triplesmapestacion
      condition:
          function: equal
          parameters:
             - [str1, $(ESTACION)]
             - [str2, $(ESTACION)]
```
be careful with the indentations in YAML! 

y así para el resto de joins
el resto está correcto

2020-10-14 18:15 UTC, isa43 commented
ultimate details

2020-10-14 21:09 UTC, dachafra approved these changes

2020-10-14 21:09 UTC, merged