HandsOn5
FacultadInformatica-LinkedData/Curso2020-2021 pull request #564
Opened 2020-10-18 17:15 UTC by jorge5799

2020-10-19 12:45 UTC, paoespinozarias requested changes
Some comments about your submission:
- Your CSV doesn't contain the column with the new URIs. 
- The YML mapping has a mistake, you need to add ~iri after the sameAs predicate otherwise you will generate a string instead of a resource in your RDF as you did now. Also, you are linking your instances with a specific value of Wikidata, but you have different values of Districts in your CSV. Also, check the links with edificio, ubicacion, and coordenadas
- The SPARQL query has a mistake (wikidata URI is a Resource).

Please, fix these comments and resubmit the assignment

2020-10-20 16:51 UTC, jorge5799 commented
Ya he cambiado lo que me pediste

2020-10-21 09:53 UTC, paoespinozarias requested changes
Decir que una instancia de Punto_recarga es lo mismo que una instancia de Distrito no es correcto. Para hacer un correcto enlazado tendrás que crear una clase Distrito en tu ontología para que la puedas instanciar y luego enlazar con los valores que has encontrado en Wikidata. Además tendrás que crear una relación nueva entre Punto_recarga y Distrito. Luego actualizar el mapping para reflejar estos cambios y regenerar el RDF.
Por favor, realiza estos cambios y reenvíalo.

2020-10-21 16:40 UTC, paoespinozarias requested changes
Muy bien, ahora el enlazado es correcto.  Sin embargo, olvidaste definir una relación nueva entre Punto_recarga y Distrito en la ontología, y por lo tanto también incluirla en el mapping para regenerar los datos correctamente. Supongo que los puntos de recarga están ubicados en un distrito.

Finalmente, tienes que actualizar la SPARQL query porque el enlazado ahora está definido para la clase Distrito en lugar de la propiedad.

2020-10-22 15:32 UTC, paoespinozarias approved these changes
Now your assignment is ok. Well done!

2020-10-22 15:32 UTC, merged